### PR TITLE
Update newpoints.php

### PR DESCRIPTION
**Pull request by donqq**
removed the e modifier, made it compatible with php 7 , replaced all the preg_replace functions with preg_replace_callback. what it fixed? before fixing the problem, couldn't post threads as it returns a warning message, quick post didn't work, users couldn't collect points, but now all are fixed with this update.

### CODE REVIEW

**Comment by PirataNervo** [comment]
Thanks :)

**Comment by stormyqq** [comment]
no problem :)

**Comment by Eldenroot** [comment]
So is this plugin compatible with php 7.0 or even better with php 7.3?

@Sama34 @DiogoParrinha 

Thx!

**Comment by Sama34** [comment]
I have been developing some plugins over PHP 7.4 (or 7.3) and I haven't found any particular issue myself.

**Comment by DiogoParrinha** [comment]
Closing this as I believe this has already been fixed a while ago

**Pull request closed without merging**
